title: Dominic Wood
description: A portfolio of projects and documentation by Dominic
remote_theme: just-the-docs/just-the-docs
color_scheme: light
favicon_ico: /assets/favicon.png
search_enabled: false
baseurl: "/portfolio"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
