title: Dominic Wood
description: A portfolio of projects and documentation by Dominic
remote_theme: just-the-docs/just-the-docs
favicon_ico: /assets/favicon.png
color_scheme: light

baseurl: "/portfolio"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
