title: Dominic Wood
description: A portfolio of projects and documentation by Dominic
theme: just-the-docs
favicon: /assets/favicon.ico

# Set the base path if using a project repo (not username.github.io)
baseurl: "/portfolio"

# Optional features
color_scheme: light

# Build settings
plugins:
  - jekyll-feed
